name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Tests
      run: pytest tests

    - name: Static code analysis (flake8)
      run: pip install flake8 && flake8 src app

    - name: Auto-format check (black)
      run: pip install black && black --check src app

    - name: Secret scanning (Gitleaks)
      uses: zricethezav/gitleaks-action@v2.0.6

    - name: DAST scan (OWASP ZAP baseline)
      uses: zaproxy
