apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
type: Opaque
stringData:
  EMAIL_USER: your_email@gmail.com
  EMAIL_PASSWORD: your_app_password
  ALERT_RECIPIENT: recipient@example.com
  SLACK_WEBHOOK: https://hooks.slack.com/services/your/webhook/url
