apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: ghcr.io/Ashwani-DevOps/genai-dashboard:latest
        ports:
        - containerPort: 8501
        envFrom:
        - secretRef:
            name: streamlit-secrets
